{
 "title": "OBITO Store Monitoring Dashboard",
 "tags": [
  "library",
  "devops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Backend CPU Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m])",
     "legendFormat": "CPU user seconds"
    }
   ]
  },
  {
   "title": "Backend Memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident memory bytes" }
   ]
  },
  {
   "title": "Backend Availability",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"library-backend\"}",
     "legendFormat": "backend up"
    }
   ]
  }
 ]
}